//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerJava.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSG", Namespace="http://schemas.datacontract.org/2004/07/WCF_Contract")]
    [System.SerializableAttribute()]
    public partial class MSG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecryptionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DecryptionCode {
            get {
                return this.DecryptionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DecryptionCodeField, value) != true)) {
                    this.DecryptionCodeField = value;
                    this.RaisePropertyChanged("DecryptionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentGUID {
            get {
                return this.DocumentGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentGUIDField, value) != true)) {
                    this.DocumentGUIDField = value;
                    this.RaisePropertyChanged("DocumentGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretInformation {
            get {
                return this.SecretInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretInformationField, value) != true)) {
                    this.SecretInformationField = value;
                    this.RaisePropertyChanged("SecretInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceJavaReceiver")]
    public interface IServiceJavaReceiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJavaReceiver/correctCodeFound", ReplyAction="http://tempuri.org/IServiceJavaReceiver/correctCodeFoundResponse")]
        void correctCodeFound(ServerJava.ServiceReference1.MSG msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJavaReceiver/correctCodeFound", ReplyAction="http://tempuri.org/IServiceJavaReceiver/correctCodeFoundResponse")]
        System.Threading.Tasks.Task correctCodeFoundAsync(ServerJava.ServiceReference1.MSG msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceJavaReceiverChannel : ServerJava.ServiceReference1.IServiceJavaReceiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceJavaReceiverClient : System.ServiceModel.ClientBase<ServerJava.ServiceReference1.IServiceJavaReceiver>, ServerJava.ServiceReference1.IServiceJavaReceiver {
        
        public ServiceJavaReceiverClient() {
        }
        
        public ServiceJavaReceiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceJavaReceiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJavaReceiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJavaReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void correctCodeFound(ServerJava.ServiceReference1.MSG msg) {
            base.Channel.correctCodeFound(msg);
        }
        
        public System.Threading.Tasks.Task correctCodeFoundAsync(ServerJava.ServiceReference1.MSG msg) {
            return base.Channel.correctCodeFoundAsync(msg);
        }
    }
}
