//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceJavaReceiver")]
    public interface IServiceJavaReceiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJavaReceiver/correctCodeFound", ReplyAction="http://tempuri.org/IServiceJavaReceiver/correctCodeFoundResponse")]
        void correctCodeFound(WCF_Contract.MSG msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJavaReceiver/correctCodeFound", ReplyAction="http://tempuri.org/IServiceJavaReceiver/correctCodeFoundResponse")]
        System.Threading.Tasks.Task correctCodeFoundAsync(WCF_Contract.MSG msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceJavaReceiverChannel : Server.ServiceReference1.IServiceJavaReceiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceJavaReceiverClient : System.ServiceModel.ClientBase<Server.ServiceReference1.IServiceJavaReceiver>, Server.ServiceReference1.IServiceJavaReceiver {
        
        public ServiceJavaReceiverClient() {
        }
        
        public ServiceJavaReceiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceJavaReceiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJavaReceiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJavaReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void correctCodeFound(WCF_Contract.MSG msg) {
            base.Channel.correctCodeFound(msg);
        }
        
        public System.Threading.Tasks.Task correctCodeFoundAsync(WCF_Contract.MSG msg) {
            return base.Channel.correctCodeFoundAsync(msg);
        }
    }
}
