//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Middleware.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/verifyData", ReplyAction="http://tempuri.org/IService2/verifyDataResponse")]
        void verifyData(string documentGUID, string code, string resultDecrryption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/verifyData", ReplyAction="http://tempuri.org/IService2/verifyDataResponse")]
        System.Threading.Tasks.Task verifyDataAsync(string documentGUID, string code, string resultDecrryption);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : Middleware.ServiceReference1.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<Middleware.ServiceReference1.IService2>, Middleware.ServiceReference1.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void verifyData(string documentGUID, string code, string resultDecrryption) {
            base.Channel.verifyData(documentGUID, code, resultDecrryption);
        }
        
        public System.Threading.Tasks.Task verifyDataAsync(string documentGUID, string code, string resultDecrryption) {
            return base.Channel.verifyDataAsync(documentGUID, code, resultDecrryption);
        }
    }
}
